import React from 'react';
import './FloatingCoffeeButton.css';

const FloatingCoffeeButton: React.FC = () => {

  // 1. Utility function to dynamically load the Razorpay script
  const loadRazorpayScript = () => {
    return new Promise((resolve) => {
      const script = document.createElement('script');
      script.src = 'https://checkout.razorpay.com/v1/checkout.js';
      script.onload = () => resolve(true);
      script.onerror = () => resolve(false);
      document.body.appendChild(script);
    });
  };

  const handlePayment = async () => {
    // 2. Load the script
    const res = await loadRazorpayScript();
    if (!res) {
      alert('Razorpay SDK failed to load. Please check your connection.');
      return;
    }

    try {
      // 3. Ask your Node.js backend to create an order
      const data = await fetch('http://localhost:5001/create-order', { 
        method: 'POST',
        headers: { 'Content-Type': 'application/json' }
      }).then((t) => t.json());

      // 4. Set up the Razorpay Checkout Options
      const options = {
        key: process.env.REACT_APP_RAZORPAY_KEY_ID, // Enter your Test Key ID here
        amount: data.amount,
        currency: data.currency,
        name: "Shreyash Kale",
        description: "Support my work",
        order_id: data.id, // The secure ID generated by your backend
        handler: function (response: any) {
          // This function triggers when the user successfully pays
          alert(`Thank you! Payment successful.\nPayment ID: ${response.razorpay_payment_id}`);
          console.log("Success Response:", response);
        },
        prefill: {
          name: "John Doe", 
          email: "john@example.com",
          contact: "9999999999"
        },
        theme: {
          color: "#FFDD00" // Matches our button color
        },
        config: {
          display: {
            blocks: {
              upi: {
                name: "Pay via UPI",
                instruments: [
                  {
                    method: "upi"
                  }
                ]
              }
            },
            sequence: ["block.upi"],
            preferences: {
              show_default_blocks: true // This still allows cards/wallets as a fallback
            }
          }
        }
      };

      // 5. Open the checkout window
      const paymentObject = new (window as any).Razorpay(options);
      paymentObject.open();

    } catch (error) {
      console.error("Payment failed to initialize:", error);
      alert("Something went wrong while setting up the payment.");
    }
  };

  return (
    <button 
      onClick={handlePayment} 
      className="floating-coffee-btn"
      aria-label="Support my work - Buy me a coffee"
    >
      <span className="coffee-icon">☕</span>
      <span className="coffee-text">Buy me a coffee</span>
    </button>
  );
};

export default FloatingCoffeeButton;