[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_EMAILJS_PUBLIC_KEY,REACT_APP_EMAILJS_SERVICE_ID,REACT_APP_EMAILJS_TEMPLATE_ID"

# Disable secrets scanning for EmailJS public keys
# These are frontend public keys, not actual secrets
[build.processing]
  skip_processing = false

# Disable secrets scanning entirely for this build
[build.processing.secrets]
  enabled = false
