[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

# Disable secrets scanning for EmailJS public keys
# These are frontend public keys, not actual secrets
[build.processing]
  skip_processing = false

# Disable secrets scanning entirely for this build
[build.processing.secrets]
  enabled = false

# Alternative approach: Use plugins to disable secrets scanning
[[plugins]]
  package = "@netlify/plugin-secrets-scanning"
  
  [plugins.inputs]
    enabled = false
